//protoc hashring.proto --go-grpc_out=./ --go_out=./

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: hashring.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_hashring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_hashring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_hashring_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Data          *string                `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_hashring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_hashring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_hashring_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *Data) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

type KeyData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyData) Reset() {
	*x = KeyData{}
	mi := &file_hashring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyData) ProtoMessage() {}

func (x *KeyData) ProtoReflect() protoreflect.Message {
	mi := &file_hashring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyData.ProtoReflect.Descriptor instead.
func (*KeyData) Descriptor() ([]byte, []int) {
	return file_hashring_proto_rawDescGZIP(), []int{2}
}

func (x *KeyData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type KeyDataList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyData       []*KeyData             `protobuf:"bytes,1,rep,name=keyData,proto3" json:"keyData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyDataList) Reset() {
	*x = KeyDataList{}
	mi := &file_hashring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyDataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDataList) ProtoMessage() {}

func (x *KeyDataList) ProtoReflect() protoreflect.Message {
	mi := &file_hashring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDataList.ProtoReflect.Descriptor instead.
func (*KeyDataList) Descriptor() ([]byte, []int) {
	return file_hashring_proto_rawDescGZIP(), []int{3}
}

func (x *KeyDataList) GetKeyData() []*KeyData {
	if x != nil {
		return x.KeyData
	}
	return nil
}

type UpdateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Err           *string                `protobuf:"bytes,2,opt,name=err,proto3,oneof" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatus) Reset() {
	*x = UpdateStatus{}
	mi := &file_hashring_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus) ProtoMessage() {}

func (x *UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_hashring_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus.ProtoReflect.Descriptor instead.
func (*UpdateStatus) Descriptor() ([]byte, []int) {
	return file_hashring_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStatus) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UpdateStatus) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_hashring_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_hashring_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_hashring_proto_rawDescGZIP(), []int{5}
}

func (x *Node) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Node) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type NodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          []*Node                `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_hashring_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_hashring_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_hashring_proto_rawDescGZIP(), []int{6}
}

func (x *NodeList) GetNode() []*Node {
	if x != nil {
		return x.Node
	}
	return nil
}

var File_hashring_proto protoreflect.FileDescriptor

const file_hashring_proto_rawDesc = "" +
	"\n" +
	"\x0ehashring.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x17\n" +
	"\x03Key\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\">\n" +
	"\x04Data\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x17\n" +
	"\x04data\x18\x02 \x01(\tH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\"/\n" +
	"\aKeyData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"1\n" +
	"\vKeyDataList\x12\"\n" +
	"\akeyData\x18\x01 \x03(\v2\b.KeyDataR\akeyData\"=\n" +
	"\fUpdateStatus\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x15\n" +
	"\x03err\x18\x02 \x01(\tH\x00R\x03err\x88\x01\x01B\x06\n" +
	"\x04_err\".\n" +
	"\x04Node\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"%\n" +
	"\bNodeList\x12\x19\n" +
	"\x04node\x18\x01 \x03(\v2\x05.NodeR\x04node2\x8e\x01\n" +
	"\tHashStore\x12\x14\n" +
	"\x03Get\x12\x04.Key\x1a\x05.Data\"\x00\x12 \n" +
	"\x03Put\x12\b.KeyData\x1a\r.UpdateStatus\"\x00\x12(\n" +
	"\aPutMany\x12\f.KeyDataList\x1a\r.UpdateStatus\"\x00\x12\x1f\n" +
	"\x06Remove\x12\x04.Key\x1a\r.UpdateStatus\"\x002\x8e\x01\n" +
	"\n" +
	"NodeStatus\x12*\n" +
	"\aAddNode\x12\x05.Node\x1a\x16.google.protobuf.Empty\"\x00\x12%\n" +
	"\vGetNodeList\x12\t.NodeList\x1a\t.NodeList\"\x00\x12-\n" +
	"\n" +
	"RemoveNode\x12\x05.Node\x1a\x16.google.protobuf.Empty\"\x00B\tZ\a./protob\x06proto3"

var (
	file_hashring_proto_rawDescOnce sync.Once
	file_hashring_proto_rawDescData []byte
)

func file_hashring_proto_rawDescGZIP() []byte {
	file_hashring_proto_rawDescOnce.Do(func() {
		file_hashring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hashring_proto_rawDesc), len(file_hashring_proto_rawDesc)))
	})
	return file_hashring_proto_rawDescData
}

var file_hashring_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hashring_proto_goTypes = []any{
	(*Key)(nil),           // 0: Key
	(*Data)(nil),          // 1: Data
	(*KeyData)(nil),       // 2: KeyData
	(*KeyDataList)(nil),   // 3: KeyDataList
	(*UpdateStatus)(nil),  // 4: UpdateStatus
	(*Node)(nil),          // 5: Node
	(*NodeList)(nil),      // 6: NodeList
	(*emptypb.Empty)(nil), // 7: google.protobuf.Empty
}
var file_hashring_proto_depIdxs = []int32{
	2, // 0: KeyDataList.keyData:type_name -> KeyData
	5, // 1: NodeList.node:type_name -> Node
	0, // 2: HashStore.Get:input_type -> Key
	2, // 3: HashStore.Put:input_type -> KeyData
	3, // 4: HashStore.PutMany:input_type -> KeyDataList
	0, // 5: HashStore.Remove:input_type -> Key
	5, // 6: NodeStatus.AddNode:input_type -> Node
	6, // 7: NodeStatus.GetNodeList:input_type -> NodeList
	5, // 8: NodeStatus.RemoveNode:input_type -> Node
	1, // 9: HashStore.Get:output_type -> Data
	4, // 10: HashStore.Put:output_type -> UpdateStatus
	4, // 11: HashStore.PutMany:output_type -> UpdateStatus
	4, // 12: HashStore.Remove:output_type -> UpdateStatus
	7, // 13: NodeStatus.AddNode:output_type -> google.protobuf.Empty
	6, // 14: NodeStatus.GetNodeList:output_type -> NodeList
	7, // 15: NodeStatus.RemoveNode:output_type -> google.protobuf.Empty
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hashring_proto_init() }
func file_hashring_proto_init() {
	if File_hashring_proto != nil {
		return
	}
	file_hashring_proto_msgTypes[1].OneofWrappers = []any{}
	file_hashring_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hashring_proto_rawDesc), len(file_hashring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_hashring_proto_goTypes,
		DependencyIndexes: file_hashring_proto_depIdxs,
		MessageInfos:      file_hashring_proto_msgTypes,
	}.Build()
	File_hashring_proto = out.File
	file_hashring_proto_goTypes = nil
	file_hashring_proto_depIdxs = nil
}
