//protoc hashring.proto --go-grpc_out=./ --go_out=./

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: hashring.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HashStore_Get_FullMethodName     = "/HashStore/Get"
	HashStore_Put_FullMethodName     = "/HashStore/Put"
	HashStore_PutMany_FullMethodName = "/HashStore/PutMany"
	HashStore_Remove_FullMethodName  = "/HashStore/Remove"
)

// HashStoreClient is the client API for HashStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HashStoreClient interface {
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Data, error)
	Put(ctx context.Context, in *KeyData, opts ...grpc.CallOption) (*UpdateStatus, error)
	PutMany(ctx context.Context, in *KeyDataList, opts ...grpc.CallOption) (*UpdateStatus, error)
	Remove(ctx context.Context, in *Key, opts ...grpc.CallOption) (*UpdateStatus, error)
}

type hashStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewHashStoreClient(cc grpc.ClientConnInterface) HashStoreClient {
	return &hashStoreClient{cc}
}

func (c *hashStoreClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Data, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Data)
	err := c.cc.Invoke(ctx, HashStore_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashStoreClient) Put(ctx context.Context, in *KeyData, opts ...grpc.CallOption) (*UpdateStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatus)
	err := c.cc.Invoke(ctx, HashStore_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashStoreClient) PutMany(ctx context.Context, in *KeyDataList, opts ...grpc.CallOption) (*UpdateStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatus)
	err := c.cc.Invoke(ctx, HashStore_PutMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashStoreClient) Remove(ctx context.Context, in *Key, opts ...grpc.CallOption) (*UpdateStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatus)
	err := c.cc.Invoke(ctx, HashStore_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashStoreServer is the server API for HashStore service.
// All implementations must embed UnimplementedHashStoreServer
// for forward compatibility.
type HashStoreServer interface {
	Get(context.Context, *Key) (*Data, error)
	Put(context.Context, *KeyData) (*UpdateStatus, error)
	PutMany(context.Context, *KeyDataList) (*UpdateStatus, error)
	Remove(context.Context, *Key) (*UpdateStatus, error)
	mustEmbedUnimplementedHashStoreServer()
}

// UnimplementedHashStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHashStoreServer struct{}

func (UnimplementedHashStoreServer) Get(context.Context, *Key) (*Data, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedHashStoreServer) Put(context.Context, *KeyData) (*UpdateStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedHashStoreServer) PutMany(context.Context, *KeyDataList) (*UpdateStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method PutMany not implemented")
}
func (UnimplementedHashStoreServer) Remove(context.Context, *Key) (*UpdateStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedHashStoreServer) mustEmbedUnimplementedHashStoreServer() {}
func (UnimplementedHashStoreServer) testEmbeddedByValue()                   {}

// UnsafeHashStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashStoreServer will
// result in compilation errors.
type UnsafeHashStoreServer interface {
	mustEmbedUnimplementedHashStoreServer()
}

func RegisterHashStoreServer(s grpc.ServiceRegistrar, srv HashStoreServer) {
	// If the following call panics, it indicates UnimplementedHashStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HashStore_ServiceDesc, srv)
}

func _HashStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashStore_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashStoreServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashStore_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashStoreServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashStore_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashStoreServer).Put(ctx, req.(*KeyData))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashStore_PutMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyDataList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashStoreServer).PutMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashStore_PutMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashStoreServer).PutMany(ctx, req.(*KeyDataList))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashStore_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashStoreServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashStore_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashStoreServer).Remove(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

// HashStore_ServiceDesc is the grpc.ServiceDesc for HashStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HashStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HashStore",
	HandlerType: (*HashStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _HashStore_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _HashStore_Put_Handler,
		},
		{
			MethodName: "PutMany",
			Handler:    _HashStore_PutMany_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _HashStore_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashring.proto",
}

const (
	NodeStatus_AddNode_FullMethodName     = "/NodeStatus/AddNode"
	NodeStatus_GetNodeList_FullMethodName = "/NodeStatus/GetNodeList"
	NodeStatus_RemoveNode_FullMethodName  = "/NodeStatus/RemoveNode"
)

// NodeStatusClient is the client API for NodeStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeStatusClient interface {
	AddNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetNodeList(ctx context.Context, in *NodeList, opts ...grpc.CallOption) (*NodeList, error)
	RemoveNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type nodeStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeStatusClient(cc grpc.ClientConnInterface) NodeStatusClient {
	return &nodeStatusClient{cc}
}

func (c *nodeStatusClient) AddNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NodeStatus_AddNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStatusClient) GetNodeList(ctx context.Context, in *NodeList, opts ...grpc.CallOption) (*NodeList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeList)
	err := c.cc.Invoke(ctx, NodeStatus_GetNodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeStatusClient) RemoveNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NodeStatus_RemoveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeStatusServer is the server API for NodeStatus service.
// All implementations must embed UnimplementedNodeStatusServer
// for forward compatibility.
type NodeStatusServer interface {
	AddNode(context.Context, *Node) (*emptypb.Empty, error)
	GetNodeList(context.Context, *NodeList) (*NodeList, error)
	RemoveNode(context.Context, *Node) (*emptypb.Empty, error)
	mustEmbedUnimplementedNodeStatusServer()
}

// UnimplementedNodeStatusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeStatusServer struct{}

func (UnimplementedNodeStatusServer) AddNode(context.Context, *Node) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNode not implemented")
}
func (UnimplementedNodeStatusServer) GetNodeList(context.Context, *NodeList) (*NodeList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeList not implemented")
}
func (UnimplementedNodeStatusServer) RemoveNode(context.Context, *Node) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveNode not implemented")
}
func (UnimplementedNodeStatusServer) mustEmbedUnimplementedNodeStatusServer() {}
func (UnimplementedNodeStatusServer) testEmbeddedByValue()                    {}

// UnsafeNodeStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeStatusServer will
// result in compilation errors.
type UnsafeNodeStatusServer interface {
	mustEmbedUnimplementedNodeStatusServer()
}

func RegisterNodeStatusServer(s grpc.ServiceRegistrar, srv NodeStatusServer) {
	// If the following call panics, it indicates UnimplementedNodeStatusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeStatus_ServiceDesc, srv)
}

func _NodeStatus_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStatusServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeStatus_AddNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStatusServer).AddNode(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStatus_GetNodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStatusServer).GetNodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeStatus_GetNodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStatusServer).GetNodeList(ctx, req.(*NodeList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeStatus_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeStatusServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeStatus_RemoveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeStatusServer).RemoveNode(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeStatus_ServiceDesc is the grpc.ServiceDesc for NodeStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NodeStatus",
	HandlerType: (*NodeStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNode",
			Handler:    _NodeStatus_AddNode_Handler,
		},
		{
			MethodName: "GetNodeList",
			Handler:    _NodeStatus_GetNodeList_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _NodeStatus_RemoveNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashring.proto",
}
